ShopDienThoai.Web/Models/ErrorViewModel.cs
namespace ShopDienThoai.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShopDienThoai.Web/Controllers/BrandsManagerController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDienThoai.Domain.Response;
using ShopDienThoai.Web.Ultilities;
using System.Collections.Generic;

namespace ShopDienThoai.Web.Controllers
{
    public class BrandsManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult Gets()
        {
            List<Brand> result = ApiHelper<List<Brand>>.HttpGetAsync($"{Helper.ApiUrl}api/brands/get");
            return Json(new { result });
        }

        public JsonResult Get(int id)
        {
            Brand result = ApiHelper<Brand>.HttpGetAsync($"{Helper.ApiUrl}api/brands/get/{id}");
            return Json(new { result });
        }

        public JsonResult Delete(int id)
        {
            ActionBrandResult result = ApiHelper<ActionBrandResult>.HttpGetAsync($"{Helper.ApiUrl}api/brands/delete/{id}", "DELETE");
            return Json(new { result });
        }
        public JsonResult Save([FromBody] Brand model)
        {
            ActionBrandResult result;
            if (model.Name == "")
                result = new ActionBrandResult()
                {
                    Message = "Nhập vào tên thương hiệu!"
                };
            else
                result = ApiHelper<ActionBrandResult>.HttpPostAsync($"{Helper.ApiUrl}api/brands/save", model);
            return Json(new { result });
        }
    }
}

ShopDienThoai.Web/Controllers/CategoriesManagerController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDienThoai.Domain.Response;
using ShopDienThoai.Web.Ultilities;
using System.Collections.Generic;

namespace ShopDienThoai.Web.Controllers
{
    public class CategoriesManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult Gets()
        {
            List<Category> result = ApiHelper<List<Category>>.HttpGetAsync($"{Helper.ApiUrl}api/categories/get");
            return Json(new { result });
        }

        public JsonResult Get(int id)
        {
            Category result = ApiHelper<Category>.HttpGetAsync($"{Helper.ApiUrl}api/categories/get/{id}");
            return Json(new { result });
        }

        public JsonResult Delete(int id)
        {
            ActionCategoryResult result = ApiHelper<ActionCategoryResult>.HttpGetAsync($"{Helper.ApiUrl}api/categories/delete/{id}", "DELETE");
            return Json(new { result });
        }
        public JsonResult Save([FromBody] Category model)
        {
            ActionCategoryResult result;
            if (model.Name == "")
                result = new ActionCategoryResult()
                {
                    Message = "Nhập vào tên danh mục!"
                };
            else
                result = ApiHelper<ActionCategoryResult>.HttpPostAsync($"{Helper.ApiUrl}api/categories/save", model);
            return Json(new { result });
        }
    }
}

ShopDienThoai.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShopDienThoai.Web.Models;
using System.Diagnostics;

namespace ShopDienThoai.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShopDienThoai.Web/Controllers/ImagesManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopDienThoai.Domain.Request.Images;
using ShopDienThoai.Domain.Response;
using ShopDienThoai.Web.Ultilities;

namespace ShopDienThoai.Web.Controllers
{
    public class ImagesManagerController : Controller
    {
        public JsonResult Gets()
        {
            List<Image> result = ApiHelper<List<Image>>.HttpGetAsync($"{Helper.ApiUrl}api/images/get");
            return Json(new { result });
        }

        public JsonResult Get(string id)
        {
            Image result = ApiHelper<Image>.HttpGetAsync($"{Helper.ApiUrl}api/images/get/{id}");
            return Json(new { result });
        }

        public JsonResult GetImagesByProductId(string id)
        {
            List<Image> result = ApiHelper<List<Image>>.HttpGetAsync($"{Helper.ApiUrl}api/images/getimagesbyproductid/{id}");
            return Json(new { result });
        }
        public JsonResult Delete(string id)
        {
            ActionImageResult result = ApiHelper<ActionImageResult>.HttpGetAsync($"{Helper.ApiUrl}api/images/delete/{id}", "DELETE");
            return Json(new { result });
        }
        public JsonResult Save([FromBody] UploadImagesRequest model)
        {
            var result = ApiHelper<ActionImageResult>.HttpPostAsync($"{Helper.ApiUrl}api/images/save", model);
            return Json(new { result });
        }
    }
}

ShopDienThoai.Web/Controllers/ProductsManagerController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDienThoai.Domain.Request.Products;
using ShopDienThoai.Domain.Response;
using ShopDienThoai.Web.Ultilities;
using System;
using System.Collections.Generic;

namespace ShopDienThoai.Web.Controllers
{
    public class ProductsManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult Gets()
        {
            ProductsList result = ApiHelper<ProductsList>.HttpGetAsync($"{Helper.ApiUrl}api/productslist/get");
            return Json(new { result });
        }

        public JsonResult Get(string id)
        {
            Product result = ApiHelper<Product>.HttpGetAsync($"{Helper.ApiUrl}api/products/get/{id}");
            return Json(new { result });
        }

        public JsonResult Delete(string id)
        {
            ActionProductResult result = ApiHelper<ActionProductResult>.HttpGetAsync($"{Helper.ApiUrl}api/products/delete/{id}", "DELETE");
            return Json(new { result });
        }
        public JsonResult Save([FromBody] CreateProductRequest model)
        {
            var result = ApiHelper<ActionProductResult>.HttpPostAsync($"{Helper.ApiUrl}api/products/save", model);
            return Json(new { result });
        }
    }
}

ShopDienThoai.Web/Views/CategoriesManager/Index.cshtml
@{
    ViewBag.Title = "Quản lý danh mục sản phẩm";
}
<div class="row">
    <div class="col-12 mb-3">
        <a href="javascript:void(0);" class="btn btn-info"
           onclick="AddEditCategory()"><i class="fas fa-plus"></i> Thêm danh mục</a>
    </div>
</div>
<table id="categoriesTable" class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Tên danh mục</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<!-- Modal -->
<div id="addEditCategory" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <form id="addEditCategoryForm">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <input hidden id="CategoryId" name="CategoryId">
                <div class="modal-body">
                    <div class="row form-group">
                        <div class="col-3">
                            <label>Tên danh mục:</label>
                        </div>
                        <div class="col-9">
                            <input type="text" id="CategoryName" name="CategoryName Name" class="form-control" data-rule-required="true">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-primary" onclick="category.save()">Lưu</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Huỷ</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section datatablejs{
    <environment include="Development">
        <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
        <script src="~/lib/bootbox.js/bootbox.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
    </environment>
}
@section datatablecss{
    <environment include="Development">
        <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    </environment>
}

ShopDienThoai.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ShopDienThoai.Web/Views/ProductsManager/Index.cshtml
@{
    ViewBag.Title = "Quản lý sản phẩm";
}
<div class="row">
    <div class="col-12 mb-3">
        <a href="javascript:void(0);" class="btn btn-info"
           onclick="AddEditProduct()"><i class="fas fa-plus"></i> Thêm sản phẩm</a>
    </div>
</div>
<table id="productsTable" class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Tên</th>
            <th>Hình ảnh</th>
            <th>Thương hiệu</th>
            <th>Thông số kỹ thuật</th>
            <th>Giá</th>
            <th>Tồn kho</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<!-- Modal -->
<div id="addEditProduct" class="modal fade" role="dialog">
    <div class="modal-dialog modal-xl">
        <form id="addEditProductForm">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <input hidden id="ProductId" name="ProductId">
                    <div id="imgsdata"></div>
                    <div class="row form-group">
                        <div class="col-2">
                        </div>
                        <div class="col-10" id="imgsPreview">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Ảnh sản phẩm:</label>
                        </div>
                        <div class="col-10">
                            <div class="custom-file">
                                <input id="ProductImages" name="ProductImages" type="file" class="custom-file-input form-control" data-rule-required="true" multiple>
                                <label class="custom-file-label" for="ProductImages">Choose file</label>
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Tên sản phẩm:</label>
                        </div>
                        <div class="col-10">
                            <input type="text" id="ProductName" name="ProductName" class="form-control" data-rule-required="true">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Giá (₫):</label>
                        </div>
                        <div class="col-4">
                            <input type="number" id="ProductPrice" name="ProductPrice" class="form-control" data-rule-required="true">
                        </div>
                        <div class="col-2">
                            <label>Số lượng (cái):</label>
                        </div>
                        <div class="col-4">
                            <input type="number" id="ProductRemain" name="ProductRemain" class="form-control" data-rule-required="true">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Thương hiệu:</label>
                        </div>
                        <div class="col-4">
                            <select id="ProductBrandId" name="ProductBrandId" class="form-control" data-rule-required="true">
                                <option value="">Chọn thương hiệu</option>
                            </select>
                        </div>
                        <div class="col-2">
                            <label>Danh mục:</label>
                        </div>
                        <div class="col-4">
                            <select id="ProductCategoryId" name="ProductCategoryId" class="form-control" data-rule-required="true">
                                <option value="">Chọn danh mục</option>
                            </select>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>CPU:</label>
                        </div>
                        <div class="col-4">
                            <input type="text" id="ProductCPU" name="ProductCPU" class="form-control" data-rule-required="true">
                        </div>
                        <div class="col-2">
                            <label>Màn hình:</label>
                        </div>
                        <div class="col-4">
                            <input type="text" id="ProductScreen" name="ProductScreen" class="form-control" data-rule-required="true">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Hệ điều hành:</label>
                        </div>
                        <div class="col-10">
                            <input type="text" id="ProductOS" name="ProductOS" class="form-control" data-rule-required="true">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Camera sau:</label>
                        </div>
                        <div class="col-4">
                            <input type="text" id="ProductRearCamera" name="ProductRearCamera" class="form-control" data-rule-required="true">
                        </div>
                        <div class="col-2">
                            <label>Camera trước:</label>
                        </div>
                        <div class="col-4">
                            <input type="text" id="ProductFrontCamera" name="ProductFrontCamera" class="form-control" data-rule-required="true">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Ram (GB):</label>
                        </div>
                        <div class="col-4">
                            <input type="number" id="ProductRam" name="ProductRam" class="form-control" data-rule-required="true">
                        </div>
                        <div class="col-2">
                            <label>Rom (GB):</label>
                        </div>
                        <div class="col-4">
                            <input type="number" id="ProductRom" name="ProductRom" class="form-control" data-rule-required="true">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-2">
                            <label>Bài viết mô tả:</label>
                        </div>
                        <div class="col-10">
                            <textarea id="ProductDescription" name="ProductDescription" class="form-control" data-rule-required="true"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-primary" onclick="product.save()">Lưu</a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Huỷ</button>
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <environment include="Development">
        <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
        <script src="~/lib/bootbox.js/bootbox.js"></script>
        <script src="~/lib/ekko-lightbox/ekko-lightbox.js"></script>
        <script src="~/lib/tinymce/tinymce.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.9.11/tinymce.min.js"></script>
    </environment>
    <script>
        document.getElementById("ProductImages").addEventListener("change", readFiles);

        $(document).on('click', '[data-toggle="lightbox"]', function (event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });

        $('#ProductImages').on('change', function () {
            var fileLabel = $(this).next('.custom-file-label');
            var files = $(this)[0].files;
            if (files.length > 1) {
                fileLabel.html(files.length + ' tập tin được chọn');
            }
            else if (files.length == 1) {
                fileLabel.html(files[0].name);
            }
        });

        tinymce.init({
            selector: 'textarea',
            theme: 'modern',
            plugins: ['advlist autolink lists link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons paste textcolor colorpicker textpattern imagetools'
            ],
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons',
            image_advtab: true,
            height: "400"
        });
    </script>
}
@section Styles{
    <environment include="Development">
        <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
        <link href="~/lib/ekko-lightbox/ekko-lightbox.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet" />
    </environment>
    <style>
        .remove-image {
            display: none;
            position: absolute;
            border-radius: 10em;
            padding: 2px 6px 3px;
            text-decoration: none;
            font: 700 21px/20px sans-serif;
            background: #555;
            border: 3px solid #fff;
            color: #FFF;
            box-shadow: 0 2px 6px rgba(0,0,0,0.5), inset 0 2px 4px rgba(0,0,0,0.3);
            text-shadow: 0 1px 2px rgba(0,0,0,0.5);
            -webkit-transition: background 0.5s;
            transition: background 0.5s;
        }

        .remove-image:hover {
            background: #E54E4E;
            padding: 3px 7px 5px;
        }

        .remove-image:active {
            background: #E54E4E;
        }
    </style>
}

ShopDienThoai.Web/Views/Shared/_DashboardLayout.cshtml
@*@inject SignInManager<User> signInManager
@inject UserManager<User> userManager
@inject AppDbContext context*@
@{
//User currentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
//var appSetting = (from s in context.AppSettings where s.Id == 1 select s).ToList().FirstOrDefault();
//ViewBag.Title = "Bảng điều khiển";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    @RenderSection("Styles", false)
    <link href="~/lib/css/DashboardStyles.css" rel="stylesheet" />
    @*<link rel="icon" href="~/images/@appSetting.Icon" asp-append-version="true" />*@
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Dashboard" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Bảng điều khiển</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        </div>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                @*<a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="@(!string.IsNullOrEmpty(currentUser.ProfilePicture) ? $"/images/users/{currentUser.ProfilePicture}" : "/images/users/0.png")" width="30 " height="30" class="rounded-circle" />&nbsp;@currentUser.Name
                    </a>*@
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" asp-controller="Home" asp-action="Index" target="_blank">Trang chủ</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Thoát</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Sản phẩm</div>
                        <a class="nav-link" asp-controller="ProductsManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-mobile-alt"></i></div>
                            Thiết bị
                        </a>
                        <a class="nav-link" asp-controller="CategoriesManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
                            Danh mục
                        </a>
                        <a class="nav-link" asp-controller="BrandsManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tags"></i></div>
                            Thương hiệu
                        </a>
                        <div class="sb-sidenav-menu-heading">Đơn hàng</div>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="PendingOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-hourglass-half"></i></div>
                            Chưa xử lý
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="ProcessingOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-angle-double-right"></i></div>
                            Đang xử lý
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="CompletedOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-check-circle"></i></div>
                            Đã hoàn thành
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="CanceledOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-times-circle"></i></div>
                            Đã huỷ
                        </a>
                        <div class="sb-sidenav-menu-heading">Thành viên</div>
                        <a class="nav-link" asp-controller="RolesManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-tag"></i></div>
                            Vai trò
                        </a>
                        <a class="nav-link" asp-controller="UsersManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Thành viên
                        </a>


                        <div class="sb-sidenav-menu-heading">Trang web</div>
                        <a class="nav-link" asp-controller="Dashboard" asp-action="AppSetting">
                            <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                            Cài đặt
                        </a>
                        <a class="nav-link" asp-controller="Dashboard" asp-action="EditCarousel">
                            <div class="sb-nav-link-icon"><i class="fas fa-images"></i></div>
                            Slide
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    @User.Identity.Name
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    <h2 class="text-center my-4">@ViewBag.Title</h2>
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; @DateTime.Now.Year by Trung Nguyen</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/font-awesome/js/all.js"></script>
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>
    </environment>
    <script src="~/js/dashboard.js" asp-append-version="true"></script>
    @RenderSection("Scripts", false)
</body>
</html>

ShopDienThoai.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopDienThoai.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopDienThoai.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopDienThoai.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>