ShopDienThoai/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ShopDienThoai.Models;
using ShopDienThoai.ViewModels;
using System;
using System.IO;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ShopDienThoai.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly AppDbContext context;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly ICarouselImageRepository carouselImageRepository;
        public DashboardController(IWebHostEnvironment webHostEnvironment, AppDbContext context, ICarouselImageRepository carouselImageRepository)
        {
            this.webHostEnvironment = webHostEnvironment;
            this.context = context;
            this.carouselImageRepository = carouselImageRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AppSetting()
        {
            var appSetting = (from s in context.AppSettings
                               select new AppSettingViewModel()
                               {
                                   Icon = s.Icon,
                                   Logo = s.Logo,
                                   ShortDesc = s.ShortDesc,
                                   Title = s.Title,
                                   DefaultRoleId = s.DefaultRoleId
                               }).ToList().FirstOrDefault();
            ViewBag.Roles = (from r in context.Roles select r).ToList();
            return View(appSetting);
        }
        [HttpPost]
        public IActionResult AppSetting(AppSettingViewModel model)
        {
            if (ModelState.IsValid)
            {
                var setting = context.AppSettings.FirstOrDefault();
                setting.Title = model.Title;
                setting.ShortDesc = model.ShortDesc;
                if (model.LogoFile != null)
                {
                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    string fileName = $"{Guid.NewGuid()}{Path.GetExtension(model.LogoFile.FileName)}";
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using var fs = new FileStream(filePath, FileMode.Create);
                    model.LogoFile.CopyTo(fs);

                    setting.Logo = fileName;
                    if (!string.IsNullOrEmpty(model.Logo))
                    {
                        string delFile = Path.Combine(webHostEnvironment.WebRootPath, "images", model.Logo);
                        System.IO.File.Delete(delFile);
                    }
                }
                if (model.IconFile != null)
                {
                    string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    string fileName = $"{Guid.NewGuid()}{Path.GetExtension(model.IconFile.FileName)}";
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using var fs = new FileStream(filePath, FileMode.Create);
                    model.IconFile.CopyTo(fs);

                    setting.Icon = fileName;
                    if (!string.IsNullOrEmpty(model.Icon))
                    {
                        string delFile = Path.Combine(webHostEnvironment.WebRootPath, "images", model.Icon);
                        System.IO.File.Delete(delFile);
                    }
                }
                setting.DefaultRoleId = model.DefaultRoleId;
                context.SaveChanges();
                return RedirectToAction("AppSetting");
            }
            return View();
        }
        public IActionResult RemoveCarouselImage(int id)
        {
            _ = carouselImageRepository.Remove(id);
            return RedirectToAction("EditCarousel");
        }
        [HttpGet]
        public IActionResult EditCarousel()
        {
            ViewBag.Images = carouselImageRepository.Get();
            return View();
        }
        [HttpPost]
        public IActionResult EditCarousel(EditCarouselViewModel model)
        {
            if (model.ImageFiles != null)
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images\\carousel");
                foreach (var imageFile in model.ImageFiles)
                {
                    var fileName = $"{Guid.NewGuid()}{Path.GetExtension(imageFile.FileName)}";
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using var fs = new FileStream(filePath, FileMode.Create);
                    imageFile.CopyTo(fs);

                    carouselImageRepository.Create(new CarouselImage()
                    {
                        Name = fileName
                    });
                }
            }
            return RedirectToAction("EditCarousel");
        }
    }
}

ShopDienThoai/Controllers/OrderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopDienThoai.Models;
using ShopDienThoai.Models.OrderModel;
using ShopDienThoai.Models.ProductModel;
using ShopDienThoai.Models.UserModel;
using ShopDienThoai.ViewModels.Order;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ShopDienThoai.Controllers
{
    public class OrderController : Controller
    {
        private readonly AppDbContext context;
        private readonly IProductRepository productRepository;
        private readonly IBrandRepository brandRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IOrderRepository orderRepository;
        private readonly SignInManager<User> signInManager;
        private readonly UserManager<User> userManager;
        private readonly ICustomerRepository customerRepository;
        private readonly IOrderDetailRepository orderDetailRepository;

        public OrderController(IProductRepository productRepository, IBrandRepository brandRepository, ICategoryRepository categoryRepository, AppDbContext context, SignInManager<User> signInManager, UserManager<User> userManager, IOrderRepository orderRepository, ICustomerRepository customerRepository, IOrderDetailRepository orderDetailRepository)
        {
            this.context = context;
            this.productRepository = productRepository;
            this.brandRepository = brandRepository;
            this.categoryRepository = categoryRepository;
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.orderRepository = orderRepository;
            this.customerRepository = customerRepository;
            this.orderDetailRepository = orderDetailRepository;
        }
        public IActionResult Buy(string id)
        {
            if (signInManager.IsSignedIn(User))
                return RedirectToAction("UserBuy", new { ProductId = id });
            ViewBag.ProductId = id;
            ViewBag.Product = (from p in context.Products where p.IsDeleted == false && p.ProductId == id select p).ToList().FirstOrDefault();
            return View();
        }
        [HttpGet]
        public IActionResult Order(string ProductId)
        {
            var product = (from p in context.Products where p.IsDeleted == false && p.ProductId == ProductId select p).ToList().FirstOrDefault();
            if (product.Remain == 0)
                return RedirectToAction("Index", "Home");
            var customer = new CustomerViewModel();
            if (signInManager.IsSignedIn(User))
            {
                var currentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
                customer = new CustomerViewModel()
                {
                    Name = currentUser.Name,
                    PhoneNumber = currentUser.PhoneNumber,
                    Address = currentUser.Address,
                    ProductId = ProductId
                };
            }
            ViewBag.Product = product;
            return View(customer);
        }
        [HttpPost]
        public IActionResult Order(CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User();
                if (signInManager.IsSignedIn(User))
                    user = userManager.FindByNameAsync(User.Identity.Name).Result;
                var product = (from p in context.Products where p.IsDeleted == false && p.ProductId == model.ProductId select p).ToList().FirstOrDefault();
                var customer = new Customer()
                {
                    CustomerName = model.Name,
                    Address = model.Address,
                    PhoneNumber = model.PhoneNumber,
                    UserId = signInManager.IsSignedIn(User) ? user.Id : null
                };
                var createCustomer = customerRepository.Create(customer);
                var order = new Order()
                {
                    CustomerId = createCustomer.CustomerId,
                    OrderTime = DateTime.Now,
                    Status = OrderStatus.Pending
                };
                var createOrder = orderRepository.Create(order);
                var orderDetail = new OrderDetail()
                {
                    OrderId = createOrder.OrderId,
                    ProductId = product.ProductId,
                    Price = product.Price,
                    Quantity = 1
                };
                var createOrderDetail = orderDetailRepository.Create(orderDetail);
                context.Products.Find(model.ProductId).Remain -= 1;
                context.SaveChanges();
                return RedirectToAction("OrderDetail", new { id = createOrder.OrderId });
            }
            return View();
        }
        public IActionResult OrderDetail(string id)
        {
            var orderDetail = (from o in context.Orders
                               where o.OrderId == id
                               join d in context.OrderDetails on o.OrderId equals d.OrderId
                               join c in context.Customers on o.CustomerId equals c.CustomerId
                               join p in context.Products on d.ProductId equals p.ProductId
                               select new OrderDetailViewModel()
                               {
                                   OrderId = o.OrderId,
                                   ProductId = p.ProductId,
                                   CustomerAddress = c.Address,
                                   CustomerName = c.CustomerName,
                                   CustomerPhoneNumber = c.PhoneNumber,
                                   OrderTime = o.OrderTime,
                                   CompleteTime = o.CompleteTime,
                                   ProductName = p.Name,
                                   ProductPrice = p.Price,
                                   OrderStatus = o.Status,
                                   Note = o.Note
                               }).ToList().FirstOrDefault();
            ViewBag.OrderId = id;
            ViewBag.UserOrder = (from u in context.Users
                                 join c in context.Customers on u.Id equals c.UserId
                                 join o in context.Orders on c.CustomerId equals o.CustomerId
                                 where o.OrderId == id
                                 select u).ToList().FirstOrDefault();
            return View(orderDetail);
        }
        public IActionResult Cancel(string id)
        {
            var order = (from o in context.Orders where o.OrderId == id select o).ToList().FirstOrDefault();
            if (order.Status != OrderStatus.Pending)
            {
                return RedirectToAction("Index", "Home");
            }
            var userOrder = (from u in context.Users
                             join c in context.Customers on u.Id equals c.UserId
                             join o in context.Orders on c.CustomerId equals o.CustomerId
                             where o.OrderId == id
                             select u).ToList().FirstOrDefault();

            var currentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
            if (userOrder.Id == currentUser.Id)
            {
                var editOrder = context.Orders.Find(id);
                editOrder.Status = OrderStatus.Canceled;
                editOrder.CompleteTime = DateTime.Now;
                var productId = (from p in context.Products
                               join d in context.OrderDetails on p.ProductId equals d.ProductId
                               join o in context.Orders on d.OrderId equals o.OrderId
                               where d.OrderId == id
                               select p).ToList().FirstOrDefault().ProductId;
                context.Products.Find(productId).Remain += 1;
                context.SaveChanges();
                return RedirectToAction("Orders", "Account");
            }
            return RedirectToAction("Index", "Home");
        }
        public IActionResult CheckOrder()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Edit(string id)
        {
            var order = (from o in context.Orders where o.OrderId == id select o).ToList().FirstOrDefault();
            if (order == null)
                return RedirectToAction("Index", "Home");
            var userOrder = (from u in context.Users
                             join c in context.Customers on u.Id equals c.UserId
                             join o in context.Orders on c.CustomerId equals o.CustomerId
                             where o.OrderId == id
                             select u).ToList().FirstOrDefault();
            if (!signInManager.IsSignedIn(User))
                return RedirectToAction("Index", "Home");
            var currentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
            if (currentUser.Id != userOrder.Id)
                return RedirectToAction("Index", "Home");

            var orderDetail = (from o in context.Orders
                               where o.OrderId == id
                               join d in context.OrderDetails on o.OrderId equals d.OrderId
                               join c in context.Customers on o.CustomerId equals c.CustomerId
                               join p in context.Products on d.ProductId equals p.ProductId
                               select new OrderDetailViewModel()
                               {
                                   OrderId = o.OrderId,
                                   ProductId = p.ProductId,
                                   CustomerAddress = c.Address,
                                   CustomerName = c.CustomerName,
                                   CustomerPhoneNumber = c.PhoneNumber,

ShopDienThoai/Views/Shared/_DashboardLayout.cshtml
@inject SignInManager<User> signInManager
@inject UserManager<User> userManager
@inject AppDbContext context
@{
    User currentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
    var appSetting = (from s in context.AppSettings where s.Id == 1 select s).ToList().FirstOrDefault();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    @RenderSection("lightboxcss", false)
    @RenderSection("datatablecss", false)
    @RenderSection("RemoveImageCss", false)
    <link href="~/lib/css/DashboardStyles.css" rel="stylesheet" />
    <link rel="icon" href="~/images/@appSetting.Icon" asp-append-version="true" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Dashboard" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Bảng điều khiển</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        </div>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="@(!string.IsNullOrEmpty(currentUser.ProfilePicture) ? $"/images/users/{currentUser.ProfilePicture}" : "/images/users/0.png")" width="30 " height="30" class="rounded-circle" />&nbsp;@currentUser.Name
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" asp-controller="Home" asp-action="Index" target="_blank">Trang chủ</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Thoát</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Sản phẩm</div>
                        <a class="nav-link" asp-controller="ProductsManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-mobile-alt"></i></div>
                            Thiết bị
                        </a>
                        <a class="nav-link" asp-controller="CategoriesManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
                            Danh mục
                        </a>
                        <a class="nav-link" asp-controller="BrandsManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tags"></i></div>
                            Thương hiệu
                        </a>
                        <div class="sb-sidenav-menu-heading">Đơn hàng</div>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="PendingOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-hourglass-half"></i></div>
                            Chưa xử lý
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="ProcessingOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-angle-double-right"></i></div>
                            Đang xử lý
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="CompletedOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-check-circle"></i></div>
                            Đã hoàn thành
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="CanceledOrders">
                            <div class="sb-nav-link-icon"><i class="fas fa-times-circle"></i></div>
                            Đã huỷ
                        </a>
                        <div class="sb-sidenav-menu-heading">Thành viên</div>
                        <a class="nav-link" asp-controller="RolesManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-tag"></i></div>
                            Vai trò
                        </a>
                        <a class="nav-link" asp-controller="UsersManager" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Thành viên
                        </a>


                        <div class="sb-sidenav-menu-heading">Trang web</div>
                        <a class="nav-link" asp-controller="Dashboard" asp-action="AppSetting">
                            <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                            Cài đặt
                        </a>
                        <a class="nav-link" asp-controller="Dashboard" asp-action="EditCarousel">
                            <div class="sb-nav-link-icon"><i class="fas fa-images"></i></div>
                            Slide
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    @User.Identity.Name
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    <h2 class="text-center my-4">@ViewBag.Title</h2>
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; @DateTime.Now.Year by Trung Nguyen</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/font-awesome/js/all.js"></script>
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>
    </environment>
    <script src="~/lib/js/DashboardScripts.js"></script>
    @RenderSection("Scripts", false)
    @RenderSection("ValidateScript", false)
    @RenderSection("lightboxjs", false)
    @RenderSection("datatablejs", false)
    @RenderSection("tinyMCE", false)
</body>
</html>

ShopDienThoai/Views/Shared/_HomeLayout.cshtml
@inject SignInManager<User> signInManager
@inject UserManager<User> userManager
@inject AppDbContext context

@{
    var categories = (from c in context.Categories where c.IsDeleted == false select c).ToList();
    var brands = (from b in context.Brands where b.IsDeleted == false select b).ToList();
    var maxRange = (from p in context.Products select p.Price).Max();
    var minRange = (from p in context.Products select p.Price).Min();
    var appSetting = (from s in context.AppSettings select s).ToList().FirstOrDefault();
    var title = (string) ViewBag.Title;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="UTF-8">
    <title>@(String.IsNullOrEmpty(title) ? $"{title}" : $"{title} - ")@appSetting.Title - @appSetting.ShortDesc</title>
    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/jqueryui/jquery-ui.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" rel="stylesheet" />
    </environment>
    @RenderSection("PageNotFound", false)
    @RenderSection("LoginCSS", false)
    @RenderSection("lightboxcss", false)
    @RenderSection("datatablecss", false)
    <link rel="icon" href="~/images/@appSetting.Icon" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning rounded-bottom mb-3 container font-weight-bold">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="~/images/@appSetting.Logo" alt="logo" style="height:50px;" asp-append-version="true">
        </a>
        <button class="navbar-toggler mt-2 ml-auto" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <form asp-controller="Home" asp-action="Search" class="form-inline">
                <input type="text" placeholder="Tìm sản phẩm..." name="keyWord" class="form-control" style="padding-right: 50px;">
                <button type="submit" class="btn" style="margin-left: -45px;"><i class="fa fa-search"></i></button>
            </form>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Danh mục
                    </a>
                    <div class="dropdown-menu">
                        @{
                            foreach (var category in categories)
                            {
                                <a class="dropdown-item" asp-controller="Home" asp-action="Category" asp-route-id="@category.CategoryId">@category.Name</a>
                            }
                        }
                    </div>
                </li>
                <li class="nav-item">
                    <a asp-controller="Order" asp-action="CheckOrder" class="nav-link">Kiểm tra đơn hàng</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                @if (signInManager.IsSignedIn(User))
                {
                    User currentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            <img src="@(!string.IsNullOrEmpty(currentUser.ProfilePicture) ? $"/images/users/{currentUser.ProfilePicture}" : "/images/users/0.png")" width="30 " height="30" class="rounded-circle" />&nbsp;
                            @currentUser.Name
                        </a>
                        <div class="dropdown-menu ">
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="dropdown-item" asp-controller="Dashboard" asp-action="Index">Trang quản trị</a>
                                <a class="dropdown-item" asp-controller="ProductsManager" asp-action="Create">Thêm sản phẩm</a>
                            }
                            <a class="dropdown-item" asp-controller="Account" asp-action="Index">Tài khoản</a>
                            <a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword">Đổi mật khẩu</a>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Orders">Đơn hàng</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Thoát</a>
                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Login" class="nav-link">Đăng nhập</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Register" class="nav-link">Đăng ký</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <!-- Footer -->
    <footer class="page-footer font-small blue bg-dark text-white rounded-top mt-3 container">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            © @DateTime.Now.Year Copyright by Trung Nguyen
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->
    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/jqueryui/jquery-ui.js"></script>
        <script src="~/lib/font-awesome/js/all.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>
    </environment>

    <script>
        $(function () {
            $("#slider-range").slider({
                range: true,
                min: @minRange,
                max: @maxRange,
                values: [@minRange, @maxRange],
                slide: function (event, ui) {
                    $("#amount").val(digitGrouping(ui.values[0]) + " ₫" + " - " + digitGrouping(ui.values[1]) + " ₫");
                }
            });
            $("#amount").val(digitGrouping($("#slider-range").slider("values", 0)) + " ₫" + " - " + digitGrouping($("#slider-range").slider("values", 1)) + " ₫");
        });
        digitGrouping = function (number) {
            return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
        }
        $(document).click(function () {
            $("#minPrice").val($("#slider-range").slider("values", 0));
            $("#maxPrice").val($("#slider-range").slider("values", 1));
        })
    </script>
    @RenderSection("Scripts", false)
    @RenderSection("ValidateScript", false)
    @RenderSection("lightboxjs", false)
    @RenderSection("datatablejs", false)
    @RenderSection("tinyMCE", false)
</body>
</html>